config/routes.rb
MyWebpage::Application.routes.draw do
  # MAINS CONTROLLER
  root 'mains#web_development'
	#match "web development", to:"mains#web_development", via: "get"
	get "web development", to: "mains#web_development", as: :web_development
	#match "web development", to:"mains#web_development", via: "post"
	post "web development", to: "mains#web_development", as: :web_development_post
	
	#match "motivation", to:"mains#motivation", via: "get"
	get "inspiring", to: "mains#inspiring", as: :inspiring
	#match "motivation", to:"mains#motivation", via: "post"
	post "inspiring", to: "mains#inspiring", as: :inspiring_post
	
	match "about", to: "mains#about", via: "get"
	match "books_courses", to: "mains#books_courses", via: "get"
	match "contact", to: "mains#contact", via: "get"
	match "admin", to: "mains#admin", via: "get"
	resources "mains", only: [:create,:destroy,:update,:edit]
  get '/mains/new/(:parent_id)/(:post_id)/(:post_motivation_id)', to: "mains#new", as: :new_main
  get "admin/all_comments", to: "mains#view_all_comments", as: :view_all_comments
	# Routes for contact page only
	match "create_subscriber", to: "mains#create_subscriber", via: "post"
	match "send_contact", to: "mains#send_contact", via: "post"
	# Route for form of mystory
	patch "admin/mystory/(:id)", to: "mains#edit_mystory_admin",as: :edit_mystory_admin
	# END OF MAINS CONTROLLER
	post '/mains/new/(:parent_id)/(:post_id)/(:post_motivation_id)', to: "mains#new", as: :new_main_dupa
	post "/mains/testonly", to: "mains#testonly"
	
	
	
	
	# POSTS CONTROLLER
  resources :posts
  match "create_post", to: "posts#create_post", via: "get"
  match "create_motivation", to: "posts#create_motivation", via: "get"
  match "save_motivation", to: "posts#save_motivation", via: "post"
  get "/web development/(:id)", to: "posts#learn_showpost", as: :learn_showpost
  get "motivation/(:id)", to: "posts#motivation_showpost", as: :motivation_showpost
  post "/web development/(:id)", to: "posts#learn_showpost", as: :learn_showpost_back
  post "motivation/(:id)", to: "posts#motivation_showpost", as: :motivation_showpost_back
  # FOR ADMIN WEBPAGE
  get "/admin/web development/(:id)/(:ahojmarynarzu)", to: "posts#admin_webdev", as: :admin_webdev
  get "/admin/delete_post/(:id)/(:alibaba)", to: "posts#delete_post", as: :delete_post
  get "/admin/edit_poscik/(:id)/(:alibaba)", to: "posts#edit_poscik", as: :edit_poscik
  patch "/admin/edit(:id)/(:alibaba)", to: "posts#apdejt", as: :apdejt
  get "/admin/delete_post_comment/(:comment_id)", to: "posts#delete_post_comment", as: :delete_post_comment
  get "/admin/edit_post_comment/(:comment_id)", to: "posts#edit_post_comment", as: :edit_post_comment
  patch "/admin/update_edit_post_comment/(:comment_id)", to: "posts#update_edit_post_comment", as: :update_edit_post_comment
	# END OF POSTS CONTROLLER


	# RESTS CONTROLLER
	get "projects/(:id)/(:name)", to: "rests#show_project", as: :show_project
	get "admin_show_projects/(:id)", to: "rests#admin_show_project", as: :admin_show_project
	get "admin_show_projects_delete/(:id)", to: "rests#admin_show_project_delete", as: :admin_show_project_delete
	get "creating_project", to: "rests#creating_project", as: :creating_project
	post "create_project_final", to: "rests#create_project_final", as: :create_project_final
	get "editing_project/(:id)", to: "rests#editing_project",as: :editing_project
	patch "edit_project_final/(:id)", to: "rests#edit_project_final", as: :edit_project_final
	#PRODUCT'S ROUTES
	get "admin/show_all_products", to: "rests#admin_all_products",as: :admin_all_products
	get "admin/create_new_product", to: "rests#create_new_product",as: :create_new_product
	post "admin/create_product_final", to: "rests#create_product_final",as: :create_product_final
	get "admin/edit_product/(:id)", to: "rests#edit_product", as: :edit_product
	patch "admin/final_product", to: "rests#edit_final_product", as: :edit_final_product
	patch "admin/delete_product", to: "rests#delete_product", as: :delete_product
	#CONTACT INFORMATIONS ROUTES
	get "admin/contact_information", to: "rests#contact_information",as: :contact_information
	patch "admin/contact_information_edit", to: "rests#contact_information_edit", as: :contact_information_edit
	#END OF CONTACT INFORMATIONS ROUTES 
	# END OF RESTS CONTROLLER
end

app/models/main.rb
class Main < ActiveRecord::Base
  #after_initialize :init
  belongs_to :post
  belongs_to :post_motivation
  
  before_save :default_values
  
  validates :name, :presence => { :message => "can't be blank" }
  validates :content, :presence => { :message => "can't be blank" }
  validates_length_of :name, minimum: 2, message: "is too short - minimum 2 characters"
  validates_length_of :name, maximum: 30, message: "is too long - maximum 30 characters"
  validates_length_of :content, minimum: 2, message: "is too short - minimum 2 characters"
  validates_length_of :content, maximum: 300, message: "is too long - maximum 300 characters"
  
  #def init
  # self.image_url == "public/guestpicture.png"
  # end
  
  def default_values
    self.image_url = "guestpicture.png"
  end
  
  
  acts_as_tree(order: "created_at DESC")
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def learn_webdeb
  end

  def motivation
  end

  def about
  end

  def books_courses
  end

  def contact
  end
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  before_action :authenticate, only: [:admin,:view_all_comments,:edit,:destroy,:update,:edit_mystory_admin]
  
  def web_development
    @post_all = Post.all
    @sort_reverse = @post_all.sort.reverse
  end

  def new
    @main = Main.new(parent_id: params[:parent_id],post_id: params[:post_id],post_motivation_id: params[:post_motivation_id])
    if params[:post_id].to_i > 0
      @post_selected = Post.find(params[:post_id])
    elsif params[:post_motivation_id].to_i > 0
      @post_selected = PostMotivation.find(params[:post_motivation_id])
    end
  end

  def inspiring
    @posts = PostMotivation.all
    @sort_rev = @posts.sort.reverse
  end

  def about
    @all_projects = Projectsabout.all
    @mystory = Mystory.find(1)
  end

  def books_courses
    @all_products = Product.all
  end

  def contact
    @mail = Mailinglist.new
    @contact = Contact.new
    @contactinfo = Contactinfo.find(1)
  end
  
  def create
    if params[:main][:parent_id].to_i > 0
      parent = Main.find_by_id(params[:main].delete(:parent_id))
      @main = parent.children.build(main_params)
    else
      @main = Main.create(main_params)
    end
    
    if @main.post_motivation_id > 0
      if @main.save
        redirect_to motivation_showpost_path(@main.post_motivation_id)
      else
        render :new
      end
    elsif @main.post_id > 0
      if @main.save
        redirect_to learn_showpost_path(@main.post_id)
      else
        render :new
      end
    end
    
  end
  
  def create_subscriber
    @mortis = Mailinglist.new(main_params_mailing_list)
    if @mortis.valid?
      @mortis.subscribe
      redirect_to contact_path
    else
      redirect_to contact_path
    end
  end
  
  def send_contact
    @contact = Contact.new(main_params_contact)
    if @contact.valid?
      @contact.injection_to_spreadsheet
      ContactMailer.contact_mail(@contact).deliver
      redirect_to contact_path
    else
      redirect_to contact_path
    end
  end
  
  def admin
    @all_posts_webdevelopment = Post.all
    @all_posts_motivation = PostMotivation.all
    @projects_all = Projectsabout.all
    @mystory = Mystory.find(1)
    @contact_info = Contactinfo.find(1)
  end
  
  def view_all_comments
    @all_comments = Main.all
  end
  
  def destroy
    @komentarz = Main.find(params[:id])
    @komentarz.destroy
    redirect_to admin_path
  end
  
  def edit
    @comment_edit = Main.find(params[:id])
  end
  
  def update
    @comment_edit = Main.find(params[:id])
    @comment_edit.update(params[:main].permit(:name,:content))
    redirect_to admin_path
  end
  
  def edit_mystory_admin
    @mystory_edit = Mystory.find(1)
    @mystory_edit.update(edit_mystory_admin_params)
    redirect_to admin_path
  end
  
  def testonly
    # @main = Main.new(main_params)
  end
  
  private
    
    def main_params
      params.require(:main).permit(:name, :content, :image_url, :post_id, :post_motivation_id) 
    end
    
    def main_params_contact
      params.require(:contact).permit(:name,:email,:content)
    end
  
    def main_params_mailing_list
      params.require(:mailinglist).permit(:email)
    end
    
    def edit_mystory_admin_params
      params.require(:mystory).permit(:name,:body,:picture1,:picture2,:picture3)
    end
    
    def authenticate
      authenticate_or_request_with_http_basic do |name, password|
        name = ENV["ADMIN_LOGIN"] && password = ENV["ADMIN_PASSWORD"]
      end
    end
    
end

app/helpers/mains_helper.rb
module MainsHelper
  def mains_tree_for(mains)
    mains.map do |first,nested|
      render(first) + (nested.size > 0 ? content_tag(:div, mains_tree_for(nested), class: "replies") : nil)
    end.join.html_safe
  end
end

app/views/mains/_form.html.erb
<%= form_for(@main,:url => url_for(:controller => "mains", :action => "create")) do |mai| %>

	<%= mai.hidden_field :parent_id %>
	
	<%= mai.hidden_field :post_id %>
	
	<%= mai.hidden_field :post_motivation_id %>
<!-- 25 , 37x10 -->
	<div>
		<div><%= mai.label :name %></div>
		<%= mai.text_field :name, class: "textfield" %>
	</div>
	<div>
		<div><%= mai.label :content %></div>
		<%= mai.text_area :content %>
	</div>
	<div>
		<%= mai.submit "Save", :class => "submit-button" %>
	</div>
<% end %>

app/views/mains/_main.html.erb
<table class="table">
	<tbody>
		<tr>
			<td rowspan="1" style="width: 75px;" ><%= image_tag(main.image_url, :alt => "Guest picture", size: "75x75")%></td>
			<td class="comment-name">Name: <%= main.name %><br/><%= l(main.created_at, format: '%d %B %Y, %H:%M:%S')%></td>
		</tr>
		<tr>
			<td colspan="2" class="comment-body"><%= simple_format(main.content,{},{:wrapper_tag => "div"}) %></td>
		</tr>
		<tr>
			<td colspan="3">
				<% from_reply_form ||= nil %>
				<% unless from_reply_form %>
					<% if main.leaf? %>
						<small>There are no replies yet!</small>
					<% end %>
					<div><%= link_to "Reply", new_main_path(main.id,main.post_id,main.post_motivation_id) %></div>
					<div>---------</div>
					<br />
				<% end %>
			</td>
		</tr>
	</tbody>
</table>

app/views/mains/about.html.erb
<%= stylesheet_link_tag "main_css/about" %>
<% content_for(:title,"MK About") %>

<br />
<br />

<div class="font main-div">
	<center>
		<strong><%= @mystory.name %></strong>
	</center>
	<p><%= simple_format(@mystory.body,{},{:wrapper_tag => "div"}) %></p>
	
</div>

<br />
<br />

<% @all_projects.each do |project| %>
	<div class="main-div font project-div">
		<center>
			<p>Project's name:</p>
			<p>"<%= project.name %>"</p>
			<p>Visit that webpage:<br /> <span class="ale"><%= link_to project.link, project.link %></span></p>
			<p>Author: Matthew Kilan</p>
			<%= link_to(show_project_path(project.id)) do %>
				<p>CLICK TO READ MORE</p>
					<table>
						<tr>
							<td><%= image_tag(project.picture1,:alt => "picture",size: "320x240") %></td>
							<td><%= image_tag(project.picture2,:alt => "picture",size: "320x240") %></td>
						</tr>
						<tr>
							<td><%= image_tag(project.picture3,:alt => "picture",size: "320x240") %></td>
							<td><%= image_tag(project.picture4,:alt => "picture",size: "320x240") %></td>
						</tr>
					</table>
				
			<% end %>
		</center>
	</div>
	<br />
	<br />
<% end %>

app/views/mains/admin.html.erb
<%= stylesheet_link_tag "main_css/admin" %>
<% content_for(:title, "Administrator") %>
<br>
<p>Web development, list of all posts</p>
<%= link_to "Create new post", create_post_path %>
<br />
<br />
<% @all_posts_webdevelopment.sort.reverse.each do |post| %>
	<%= link_to (admin_webdev_path(post.id,true)) do %>
		<table class="database_post">
			<tr>
				<td class="id"><%= p "id: #{post.id}" %></td>
				<td class="name"><%= post.title %></td>
			</tr>
			<tr>
				<td colspan="3">
					<%= p "Date:" %>
					<%= post.date %>
				</td>
			</tr>
		</table>
	<% end %>
<% end %>

<p>Motivation, list of all posts</p>

<%= link_to "Create new post", create_motivation_path %>

<br />
<br />

<% @all_posts_motivation.sort.reverse.each do |post| %>
	<%= link_to (admin_webdev_path(post.id,false)) do %>
		<table class="database_post">
			<tr>
				<td class="id"><%= p "id: #{post.id}" %></td>
				<td class="name"><%= post.title %></td>
			</tr>
			<tr>
				<td colspan="3">
					<%= p "Date:" %>
					<%= post.date %>
				</td>
			</tr>
		</table>
	<% end %>
<% end %>

<br /><br />
<div>List of all application's comments:</div>
<p><%= link_to("Link to all comments in Web development and Motivation category",view_all_comments_path) %></p>
<br /><br />

<p>Add new projects that are completed/work in progress</p>

<p><%= link_to("Create new project description",creating_project_path)%></p>

<% @projects_all.each do |project| %>
	<%= link_to(admin_show_project_path(project.id)) do %>
		<table class="database_project">
			
			<tr>
				<td class="id"><%= p "id: #{project.id}" %></td>
				<td class="name" ><%= project.name %></td>
			</tr>
			
		</table>
	<% end %>
	<p>- - - - - - - - - - - - - - - - - - - - - - - - - - -</p>
<% end %>

<br />
<br />

<%= form_for(@mystory,:url => edit_mystory_admin_path(@mystory.id)) do |story| %>
	<div>
		<%= story.label :name %>
		<%= story.text_field :name %>
	</div>
	<div>
		<%= story.label :body %>
		<%= story.text_area :body %>
	</div>
	<div>
		<%= story.label :picture1 %>
		<%= story.text_field :picture1 %>
	</div>
	<div>
		<%= story.label :picture2 %>
		<%= story.text_field :picture2 %>
	</div>
	<div>
		<%= story.label :picture3 %>
		<%= story.text_field :picture3 %>
	</div>
	<div>
		<%= story.submit("Submit",data: {confirm: "Are you sure?"}) %>
	</div>
<% end %>

<br />
<br />

<div>Click below to see list of all books & courses</div>
<%= link_to("All books & courses",admin_all_products_path) %>

<br />
<br />

<div>Click below to edit contact informations</div>
<table>
	<tr>
		<td>Full name: <%= @contact_info.name_surname %></td>
	</tr>
	<tr>
		<td>Facebook: <%= @contact_info.facebook %></td>
	</tr>
	<tr>
		<td>Twitter: <%= @contact_info.twitter %></td>
	</tr>
	<tr>
		<td>Email address: <%= @contact_info.email_address %></td>
	</tr>
	<tr>
		<td>Phone number: <%= @contact_info.phone_number %></td>
	</tr>
	<tr>
		<td>Github: <%= @contact_info.github %></td>
	</tr>
</table>
<%= link_to("Contact informations",contact_information_path)%>

app/views/mains/books_courses.html.erb
<%= stylesheet_link_tag "main_css/book&courses" %>
<% content_for(:title,"MK Books&Courses") %>
<!--
<table class="product-table">	
	<tr>
		<td class="name">Persil Power Black</td>
		<td class="picture" rowspan="2"><%# image_tag("200jeden.jpg") %></td>
	</tr>
	<tr>
		<td class="short-desc">Jestem krotkim opisem</td>
	</tr>
	<tr>
		<td class="affiliate" colspan="2">link partnerski</td>
	</tr>
</table>
-->
<% @all_products.each do |product| %>
	<br />
	<div class="whole-div clear-fix font">
		<div class="div-picture"><%= image_tag(product.picture1,{:alt => "Picture"}) %></div>
		<div class="div-name"><b><%= product.name %></b></div>
		<div class="div-author">by <%= product.author %></div>
		<p class="div-short-desc"><%= simple_format(product.short_description,{},{:wrapper_tag => "div"}) %></p>
		<center><p class="div-affiliate"><b><%= link_to(product.affiliate_link,product.name_affiliate_link) %></b></p></center>
		<!--<center><p class="enc"><%# link_to("--\> READ MORE <--",web_development_path)%></p></center>-->
	</div>
	<center><div>- - - - - - - - - - - - - - - - - - - - - - - - - -</div></center>
<% end %>

app/views/mains/contact.html.erb
<%= stylesheet_link_tag "main_css/contact" %>
<% content_for(:title, "MK Contact") %>

<br/>
	<div class="font">
	<p>CONTACT INFORMATIONS</p>
		<div class="divs"><b>My full name:&nbsp;&nbsp;&nbsp;&nbsp;</b><%= @contactinfo.name_surname %></div>
		<div class="divs"><b>Email:&nbsp;&nbsp;&nbsp;&nbsp;</b><%= @contactinfo.email_address %></div>
		<div class="divs"><b>Phone number:&nbsp;&nbsp;&nbsp;&nbsp;</b><%= @contactinfo.phone_number %></div>
		<div class="divs"><b>Facebook:&nbsp;&nbsp;&nbsp;&nbsp;</b><%= link_to(@contactinfo.facebook,@contactinfo.facebook) %></div>
		<div class="divs"><b>Twitter:&nbsp;&nbsp;&nbsp;&nbsp;</b><%= link_to(@contactinfo.twitter,@contactinfo.twitter) %></div>
		<div class="divs"><b>Github:&nbsp;&nbsp;&nbsp;&nbsp;</b><%= link_to(@contactinfo.github,@contactinfo.github) %></div>
	</div>
	<br />	
	<br />
<center>
	<div class="newsletter">
		<br />
		<div class="font2">WANT TO SING UP FOR MY NEWSLETTER?</div>
		<div class="font2">I'll send you information announcing new posts availability</div>
		<br />
		<div class="font2">
			<%= simple_form_for(@mail,url: url_for(controller: "mains", action: "create_subscriber")) do |g| %>
				<%= g.error_notification %>
				<%= g.input :email, label: false, :placeholder => "Your email address...", :input_html => {class: "size",id: "email_mailinglist"} %>
				</br>
				<%= g.button :submit, "Sign up for the newsletter", class: "newsletter_sing-up", id: "submit_mailinglist" %>
			<% end %>
		</div>
		<br />
	</div>
	<br />
	<br />
	<div class="font3">
		<p>QUICK CONTACT FORM <br />(you'll send me an email):</p>
		<div>
			<%= simple_form_for(@contact,:url => url_for(controller: "mains", action: "send_contact")) do |f| %>
				<%= f.error_notification %>
				<div>Your name:</div><%= f.input :name, label: false, :input_html => {class: "contact_size",id: "imie"} %>
				<div>Your email:</div><%= f.input :email, label: false, :input_html => {class: "contact_size",id: "imeil"} %>
				<div>Content:</div><%= f.input :content, label: false, as: :text, :input_html => {class: "contact_form",id: "zawartosc"} %>
				<%= f.button :submit, "Submit", class: "contact_submit", id: "submitform_nr2"%>
			<% end %>
		</div>
		<br />
		<br />
		<br />
	</div>
</center>

app/views/mains/edit.html.erb
<%= stylesheet_link_tag "main_css/edit" %>
<% content_for(:title,"Edit") %>

<%= @comment_edit.inspect %>

<br />

<%= form_for :main, url: main_path(@comment_edit), method: :patch do |f| %>
	<%= f.label :title %> <br>
	<%= f.text_field :title %>  <br />
	<%= f.label :body %> <br />
	<%= f.text_area :body %> <br />
	<%= f.submit %>
<% end %>

<br />

<%= link_to "Back", admin_path %>

app/views/mains/inspiring.html.erb
<%= stylesheet_link_tag "main_css/motivation" %>
<% content_for(:title, "MK Inspiring") %>

<% @sort_rev.each do |asdf| %>
	<%= link_to(motivation_showpost_path(asdf.id),id: "inspiring_#{asdf.id}") do %>
		<div class="post">
			<div class="post_title" > <%= simple_format(asdf.title.upcase,{},{:wrapper_tag => "div"}) %></div>
			<div class="date">Release date: <%= asdf.date %></div>
			<br />
			<div class="short_desc">
				<%= simple_format(asdf.short,{},{:wrapper_tag => "div"}) %>
			</div>
		</div>
	<% end %>
	<div class="hr">- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -</div>
	<br />
<% end %>

app/views/mains/learn_webdeb.html.erb
<%= stylesheet_link_tag "main_css/webdev" %>
<% content_for(:title, "MK Web development") %>

<% @sort_reverse.each do |asdf| %>
	<%= link_to(learn_showpost_path(asdf.id)) do %>
		<div class="post">
			<div class="post_title" >> <%= asdf.title.upcase %></div>
			<div class="date">Release date: <%= asdf.date %></div>
			<br />
			<div class="short_desc">
				<%= asdf.short %>
			</div>
		</div>
	<% end %>
	<div class="hr">- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -</div>
	<br />
<% end %>

app/views/mains/motivation.html.erb
<%= stylesheet_link_tag "main_css/motivation" %>
<% content_for(:title, "MK Motivation") %>

<% @sort_rev.each do |asdf| %>
	<%= link_to(motivation_showpost_path(asdf.id)) do %>
		<div class="post">
			<div class="post_title" >> <%= asdf.title.upcase %></div>
			<div class="date">Release date: <%= asdf.date %></div>
			<br />
			<div class="short_desc">
				<%= asdf.short %>
			</div>
		</div>
	<% end %>
	<div class="hr">- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -</div>
	<br />
<% end %>

app/views/mains/new.html.erb
<% if @main.post_id.to_i > 0 %>
	<%= stylesheet_link_tag("main_css/new-webdev-comments") %>
<% elsif @main.post_motivation_id.to_i > 0 %>
	<%= stylesheet_link_tag("main_css/new-motivation-comments") %>
<% end %>

<% if @main.parent %>
		<% content_for(:title,"Reply to comment") %>
<% else %>
		<% content_for(:title,"Add comment") %>
<% end %>

<div class="margin-auto">
	<% if @main.parent %>
		<h3>Reply to comment</h3>
	<% else %>
		<h3>Add new comment</h3>
	<% end %>
	
	<% if @main.errors.any? == false %>
		<div>Post: <b><%= @post_selected.title %></b></div>
		<br />
	<% end %>
	
	
	<% if @main.errors.any? %>
	
		<% if @main.post_id.to_i > 0 %>
	    	<% @new_found_post = Post.find(@main.post_id) %>
	    <% elsif @main.post_motivation_id.to_i > 0 %>
	    	<% @new_found_post = PostMotivation.find(@main.post_motivation_id) %> 
	    <% end %>
			<div>Post: <b><%= @new_found_post.title %></b></div>
			<br />
			<div class="border">
				<div class="new-color"><%= pluralize(@main.errors.count, "error") %> prohibited this comment from being saved:</div>
				<div>
					<ul>
						<% @main.errors.full_messages.each do |msg| %>
							<li><div class="new-color"><%= msg %></div></li>
						<% end %>
					</ul>
				</div>
			</div>
			<br />
	<% end %>
	
	<% if @main.parent %>
		<%= render "main", main: @main.parent, from_reply_form: true %>
		<br />
	<% end %>
	
	<%= render :partial => "form" %>
	
	<!--
	<%# @main.inspect %>
	<br />
	<%# @post_selected.inspect %>
	-->
	
	<% if @main.post_id.to_i > 0 %>
		<%= button_to "Go back", learn_showpost_back_path(@main.post_id), :class => "submit-button" %>
	<% elsif @main.post_motivation_id.to_i > 0 %>
		<%= button_to "Go back", motivation_showpost_back_path(@main.post_motivation_id), :class => "submit-button" %>
	<% end %>
	
</div>

app/views/mains/testonly.html.erb
<%= @main.inspect %>

app/views/mains/view_all_comments.html.erb
<%= stylesheet_link_tag "main_css/admin" %>
<% content_for(:title, "Administrator") %>

<p>All comments in Web development and Motivation category:</p>
<% @all_comments.each do |komentarz| %>
	<table class="database_post">
		<tr>
			<td class="id"><%= p "id: #{komentarz.id}" %></td>
			<td class="name"><%= komentarz.name %></td>
			<td class="parent">
				<% if komentarz.parent_id == nil %>
					<%= p "parent_id: root" %>
				<% else %>
					<%= p "parent_id: #{komentarz.parent_id}" %>
				<% end %>
			</td>
		</tr>
		<tr>
			<td colspan="3" class="body">
				<%= p "Content:" %>
				<%= komentarz.content %>
			</td>
		</tr>
		<tr>
			<td colspan="3"><%= link_to "Delete", main_path(komentarz),method: :delete, data: { confirm: "Are you sure?" }  %></td>
		</tr>
		<tr>
			<td colspan="3"><%= link_to "Edit", edit_main_path(komentarz) %></td>
		</tr>
	</table>
<% end %>

app/views/mains/web_development.html.erb
<%= stylesheet_link_tag "main_css/webdev" %>
<% content_for(:title, "MK Web development") %>

<% @sort_reverse.each do |asdf| %>
	<%= link_to(learn_showpost_path(asdf.id), id: "web_development_#{asdf.id}") do %>
		<div class="post">
			<div class="post_title" > <%= simple_format(asdf.title.upcase,{},{:wrapper_tag => "div"}) %></div>
			<div class="date">Release date: <%= asdf.date %></div>
			<div class="short_desc">
				<%= simple_format(asdf.short,{},{wrapper_tag: "div"}) %>
			</div>
		</div>
	<% end %>
	<div class="hr">- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -</div>
	<br />
<% end %>