config/routes.rb
MyWebpage::Application.routes.draw do
  # MAINS CONTROLLER
  root 'mains#web_development'
	#match "web development", to:"mains#web_development", via: "get"
	get "web development", to: "mains#web_development", as: :web_development
	#match "web development", to:"mains#web_development", via: "post"
	post "web development", to: "mains#web_development", as: :web_development_post
	
	#match "motivation", to:"mains#motivation", via: "get"
	get "inspiring", to: "mains#inspiring", as: :inspiring
	#match "motivation", to:"mains#motivation", via: "post"
	post "inspiring", to: "mains#inspiring", as: :inspiring_post
	
	match "about", to: "mains#about", via: "get"
	match "books_courses", to: "mains#books_courses", via: "get"
	match "contact", to: "mains#contact", via: "get"
	match "admin", to: "mains#admin", via: "get"
	resources "mains", only: [:create,:destroy,:update,:edit]
  get '/mains/new/(:parent_id)/(:post_id)/(:post_motivation_id)', to: "mains#new", as: :new_main
  get "admin/all_comments", to: "mains#view_all_comments", as: :view_all_comments
	# Routes for contact page only
	match "create_subscriber", to: "mains#create_subscriber", via: "post"
	match "send_contact", to: "mains#send_contact", via: "post"
	# Route for form of mystory
	patch "admin/mystory/(:id)", to: "mains#edit_mystory_admin",as: :edit_mystory_admin
	# END OF MAINS CONTROLLER
	post '/mains/new/(:parent_id)/(:post_id)/(:post_motivation_id)', to: "mains#new", as: :new_main_dupa
	post "/mains/testonly", to: "mains#testonly"
	
	
	
	
	# POSTS CONTROLLER
  resources :posts
  match "create_post", to: "posts#create_post", via: "get"
  match "create_motivation", to: "posts#create_motivation", via: "get"
  match "save_motivation", to: "posts#save_motivation", via: "post"
  get "/web development/(:id)", to: "posts#learn_showpost", as: :learn_showpost
  get "motivation/(:id)", to: "posts#motivation_showpost", as: :motivation_showpost
  post "/web development/(:id)", to: "posts#learn_showpost", as: :learn_showpost_back
  post "motivation/(:id)", to: "posts#motivation_showpost", as: :motivation_showpost_back
  # FOR ADMIN WEBPAGE
  get "/admin/web development/(:id)/(:ahojmarynarzu)", to: "posts#admin_webdev", as: :admin_webdev
  get "/admin/delete_post/(:id)/(:alibaba)", to: "posts#delete_post", as: :delete_post
  get "/admin/edit_poscik/(:id)/(:alibaba)", to: "posts#edit_poscik", as: :edit_poscik
  patch "/admin/edit(:id)/(:alibaba)", to: "posts#apdejt", as: :apdejt
  get "/admin/delete_post_comment/(:comment_id)", to: "posts#delete_post_comment", as: :delete_post_comment
  get "/admin/edit_post_comment/(:comment_id)", to: "posts#edit_post_comment", as: :edit_post_comment
  patch "/admin/update_edit_post_comment/(:comment_id)", to: "posts#update_edit_post_comment", as: :update_edit_post_comment
	# END OF POSTS CONTROLLER


	# RESTS CONTROLLER
	get "projects/(:id)/(:name)", to: "rests#show_project", as: :show_project
	get "admin_show_projects/(:id)", to: "rests#admin_show_project", as: :admin_show_project
	get "admin_show_projects_delete/(:id)", to: "rests#admin_show_project_delete", as: :admin_show_project_delete
	get "creating_project", to: "rests#creating_project", as: :creating_project
	post "create_project_final", to: "rests#create_project_final", as: :create_project_final
	get "editing_project/(:id)", to: "rests#editing_project",as: :editing_project
	patch "edit_project_final/(:id)", to: "rests#edit_project_final", as: :edit_project_final
	#PRODUCT'S ROUTES
	get "admin/show_all_products", to: "rests#admin_all_products",as: :admin_all_products
	get "admin/create_new_product", to: "rests#create_new_product",as: :create_new_product
	post "admin/create_product_final", to: "rests#create_product_final",as: :create_product_final
	get "admin/edit_product/(:id)", to: "rests#edit_product", as: :edit_product
	patch "admin/final_product", to: "rests#edit_final_product", as: :edit_final_product
	patch "admin/delete_product", to: "rests#delete_product", as: :delete_product
	#CONTACT INFORMATIONS ROUTES
	get "admin/contact_information", to: "rests#contact_information",as: :contact_information
	patch "admin/contact_information_edit", to: "rests#contact_information_edit", as: :contact_information_edit
	#END OF CONTACT INFORMATIONS ROUTES 
	# END OF RESTS CONTROLLER
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :mains, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate, only: [:update_edit_post_comment,:edit_post_comment,:delete_post_comment,:create,
  :save_motivation,:create_post,:create_motivation,:admin_webdev,:delete_post,:edit_poscik,:apdejt]
  
  def create
    @post_created = Post.new(post_param_create_post)
    @post_created.save
    if @post_created.save
      redirect_to admin_path
    else
      redirect_to admin_path
    end
  end
  
  def save_motivation
    @post_moti_created = PostMotivation.new(post_motivation_param)
    @post_moti_created.save
    if @post_moti_created.save
      redirect_to admin_path
    else
      redirect_to admin_path
    end
  end
  
  def create_post
    @post_new = Post.new
  end
  
  def create_motivation
    @post_new = PostMotivation.new
  end
  
  def learn_showpost
    #@post_to_render = Post.where(id: params[:id]) - zostawiam tego dla przestrogi, nie moglem w learn_showpost drukowac na ekran poszczegolnych parametrow tego posta pomimo, ze zawieral wszystkie parametry w srodku.
    @post_to_render2 = Post.find(params[:id])
    @mains = Main.where(post_id: params[:id]).hash_tree
  end
  
  def motivation_showpost
    @post_to_render3 = PostMotivation.find(params[:id])
    @mains = Main.where(post_motivation_id: params[:id]).hash_tree
  end
  
  def admin_webdev
    @alibaba = params[:ahojmarynarzu]
    if @alibaba == "true"
      @received_post = Post.find(params[:id])
      @all_post_comments = Main.where(post_id: params[:id]).all
    elsif @alibaba == "false"
      @received_post = PostMotivation.find(params[:id])
      @all_post_comments = Main.where(post_motivation_id: params[:id]).all
    end
  end
  
  def delete_post
    @alibaba = params[:alibaba]
    if @alibaba == "true"
      #@to_delete_post = Post.find(params[:id])
      #@comments_deleted = Main.where(post_id: params[:id])
      #@comments_deleted.destroy_all
      #@to_delete_post.destroy
      #redirect_to admin_path
      
      Post.find(params[:id]).destroy
      redirect_to admin_path
      
      #@to_delete_post = Post.find(params[:id])
      #Main.delete_all(post_id: params[:id])
      #@to_delete_post.destroy
      #redirect_to admin_path
    elsif @alibaba == "false"
      #@to_delete_post = PostMotivation.find(params[:id])
      #@comments_deleted = Main.where(post_motivation_id: params[:id])
      #@comments_deleted.destroy_all
      #@to_delete_post.destroy
      #redirect_to admin_path
      
      PostMotivation.find(params[:id]).destroy
      redirect_to admin_path
      
      #@to_delete_post = PostMotivation.find(params[:id])
      #Main.delete_all(post_motivation_id: params[:id])
      #@to_delete_post.destroy
      #redirect_to admin_path
    end
  end
  
  def edit_poscik
    @alibaba = params[:alibaba]
    if @alibaba == "true"
      @post_to_edit = Post.find(params[:id])
    elsif @alibaba == "false"
      @post_to_edit = PostMotivation.find(params[:id])
    end
  end
  
  def apdejt
    @alibaba = params[:alibaba]
    if @alibaba == "true"
      @about_to_be_edited = Post.find(params[:id])
      @about_to_be_edited.update(edit_post_webdev_params)
      redirect_to admin_path
    elsif @alibaba == "false"
      @about_to_be_edited = PostMotivation.find(params[:id])
      @about_to_be_edited.update(edit_post_moti_params)
      redirect_to admin_path
    end
  end
  
  def delete_post_comment
    @comment_to_be_deleted = Main.find(params[:comment_id])
    @comment_to_be_deleted.destroy
    redirect_to admin_path
  end
  
  def edit_post_comment
    @comment_to_be_edited = Main.find(params[:comment_id])
  end
  
  def update_edit_post_comment
    @comment_to_be_updated = Main.find(params[:comment_id])
    @comment_to_be_updated.update(update_post_comment_params)
    redirect_to admin_path
  end
  
  private
  
    def post_param_create_post
      params.require(:post).permit(:title,:date,:short,:body)
    end
    
    def post_motivation_param
      params.require(:post_motivation).permit(:title,:date,:short,:body)
    end

    #UNIQUE PARAMS FOR EDITING POSTS
      def edit_post_webdev_params
        params.require(:post).permit(:title,:date,:short,:body)
      end

      def edit_post_moti_params
        params.require(:post_motivation).permit(:title,:date,:short,:body)
      end
    #END OF UNIQUE PARAMS FOR EDITING POSTS
    
    #PARAMS FOR EDITING POST'S COMMENT
      def update_post_comment_params
        params.require(:main).permit(:name,:content)
      end
    #END OF PARAMS FOR EDITING POST'S COMMENT
    
    def authenticate
      authenticate_or_request_with_http_basic do |name, password|
        name = ENV["ADMIN_LOGIN"] && password == ENV["ADMIN_PASSWORD"]
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/admin_webdev.html.erb
<%= stylesheet_link_tag "main_css/admin_webdev" %>
<% content_for(:title, "Admin - webdev")%>

<%= @received_post.inspect %>
</br>
<%= @alibaba.inspect %>
<br />

<table class="database_post">
	<tr>
		<td class="id">
			<%= @received_post.id %>
		</td>
		<td class="name">
			<%= @received_post.title %>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<%= @received_post.short %>
		</td>
	</tr>
	<tr>
		<td colspan="2" class="body">
			<%= @received_post.body %>
		</td>
	</tr>
	<tr>
		<td>
			<%= @received_post.date %>
		</td>
	</tr>
	<tr>
		<td>
			<%= link_to "Edit", edit_poscik_path(@received_post.id,@alibaba) %>
		</td>
	</tr>
	<tr>
		<td>
			<%= link_to "Delete", delete_post_path(@received_post.id,@alibaba), data: { confirm: "Are you sure? This post and all it's corrensponding comments will be deleted" } %>
		</td>
	</tr>
</table>

<br />
<br />

<% @all_post_comments.each do |comment| %>
	<table>
		<tr>
			<td><%= comment.id %></td>
			<td><%= comment.name %></td>
			<td>
				<% if comment.parent_id == nil %>
					<%= p "parent_id: root" %>
				<% else %>
					<%= p "parent_id: #{comment.parent_id}" %>
				<% end %>
			</td>
		</tr>
		<tr>
			<td colspan="3">
				<%= p "Content:" %>
				<%= comment.content %>
			</td>
		</tr>
		<tr>
			<td colspan="3"><%= link_to "Delete", delete_post_comment_path(comment.id), data: { confirm: "Are you sure?" }  %></td>
		</tr>
		<tr>
			<td colspan="3"><%= link_to "Edit", edit_post_comment_path(comment.id) %></td>
		</tr>
	</table>
	<br />
<% end %>

app/views/posts/create_motivation.html.erb
<% content_for(:title, "Post motivation") %>

<%= form_for(@post_new, :url => url_for(:controller => "posts", :action => "save_motivation")) do |newpost| %>
	<div>
		<%= newpost.label :title %>
		<br />
		<%= newpost.text_field :title%>
	</div>
	<div>
		<%= newpost.label :short %>
		<br />
		<%= newpost.text_area :short %>
	</div>
	<div>
		<%= newpost.label :body %>
		<br />
		<%= newpost.text_area :body %>
	</div>
	<div>
		<%= newpost.label :date %>
		<br />
		<%= newpost.text_field :date %>
	</div>
	<div>
		<%= newpost.submit "Create new post" %>
	</div>
<% end %>
<br>
<%= link_to "Back", admin_path %>

app/views/posts/create_post.html.erb
<% content_for(:title, "Post webdevelopment") %>

<%= form_for(@post_new, :url => url_for(:controller => "posts", :action => "create")) do |newpost| %>
	<div>
		<%= newpost.label :title %>
		<br />
		<%= newpost.text_field :title%>
	</div>
	<div>
		<%= newpost.label :short %>
		<br />
		<%= newpost.text_area :short %>
	</div>
	<div>
		<%= newpost.label :body %>
		<br />
		<%= newpost.text_area :body %>
	</div>
	<div>
		<%= newpost.label :date %>
		<br />
		<%= newpost.text_field :date %>
	</div>
	<div>
		<%= newpost.submit "Create new post" %>
	</div>
<% end %>
<br>
<%= link_to "Back", admin_path %>

app/views/posts/edit_poscik.html.erb
<% content_for(:title, "Edit post") %>

<%= @post_to_edit.inspect %>
<br />
<%= form_for(@post_to_edit,:url => apdejt_path(@post_to_edit.id,@alibaba)) do |post_edit| %>
	<div><%= post_edit.label :title %></div>
	<div><%= post_edit.text_field :title %></div>
	<br />
	<div><%= post_edit.label :short %></div>
	<div><%= post_edit.text_area :short %></div>
	<br />
	<div><%= post_edit.label :body %></div>
	<div><%= post_edit.text_area :body %></div>
	<br />
	<div><%= post_edit.label :date %></div>
	<div><%= post_edit.text_field :date %></div>
	<br />
	<div><%= post_edit.submit "Submit" %></div>
<% end %>

app/views/posts/edit_post_comment.html.erb
<% content_for(:title, "Edit certain post")%>

<%= @comment_to_be_edited.inspect %>

<%= form_for(@comment_to_be_edited, :url => update_edit_post_comment_path(@comment_to_be_edited.id)) do |comment| %>
	<br />
	<div><%= comment.label :name %></div>
	<div><%= comment.text_field :name %></div>
	<br />
	<div><%= comment.label :content %></div>
	<div><%= comment.text_area :content %></div>
	<br />
	<div><%= comment.submit "Submit " %></div>
<% end %>

app/views/posts/learn_showpost.html.erb
<% content_for(:title,"MK #{@post_to_render2.title}") %>
<%= stylesheet_link_tag("main_css/learn_showpost") %>
<!--<div><%# button_to "Go back", learn_webdeb_path %></div>-->
<div class="post">
	<div class="post_title" ><%= simple_format(@post_to_render2.title.upcase,{},{:wrapper_tag => "div"}) %></div>
	<div class="date">Release date: <%= @post_to_render2.date %></div>
	<br />
	<div class="long_desc">
		<%= simple_format(@post_to_render2.body,{},{:wrapper_tag => "div"}) %>
	</div>
	<div class="hr">- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -</div>
	<!--<p><%# link_to("Add new comment!",new_main_path(0,@post_to_render2.id,0), class: "link") %></p>-->
	<center>
		<p><%= button_to "Add new comment!", new_main_dupa_path(0,@post_to_render2.id,0), class: "button", id: "add_comment" %></p>
	</center>
</div>
<br />
<br />
<span class="all-posts-comments"><%= mains_tree_for @mains %></span>

app/views/posts/motivation_showpost.html.erb
<%= stylesheet_link_tag("main_css/motivation_showpost")%>
<% content_for(:title,"MK #{@post_to_render3.title}") %>

<!--<div><%# button_to("Go back",motivation_path) %></div>-->
<div class="post">	
	<div class="post_title"><%= simple_format(@post_to_render3.title.upcase,{},{:wrapper_tag => "div"}) %></div>
	<span class="date">Release date: <%= @post_to_render3.date %></span>
	<br />
	<div class="long_desc">
		<%= simple_format(@post_to_render3.body,{},{:wrapper_tag => "div"}) %>
	</div>
	<div class="hr">- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -</div>
	<!--<p><%# link_to("Add new comment!",new_main_path(0,0,@post_to_render3.id), class: "link") %></p>-->
	<center>
		<!--  <p><%= button_to "Add new comment!", new_main_dupa_path(0,0,@post_to_render3.id), class: "button",id: "add_comment",js: true %></p> -->
		<%= button_to new_main_dupa_path(0,0,@post_to_render3.id), class: "button",id: "add_comment" do %>
			Add new comment!
		<% end %>
	</center>
</div>	

<br />
<br />
<span class="all-posts-comments"><%= mains_tree_for @mains %></span>