config/routes.rb
MyWebpage::Application.routes.draw do
  # MAINS CONTROLLER
  root 'mains#web_development'
	#match "web development", to:"mains#web_development", via: "get"
	get "web development", to: "mains#web_development", as: :web_development
	#match "web development", to:"mains#web_development", via: "post"
	post "web development", to: "mains#web_development", as: :web_development_post
	
	#match "motivation", to:"mains#motivation", via: "get"
	get "inspiring", to: "mains#inspiring", as: :inspiring
	#match "motivation", to:"mains#motivation", via: "post"
	post "inspiring", to: "mains#inspiring", as: :inspiring_post
	
	match "about", to: "mains#about", via: "get"
	match "books_courses", to: "mains#books_courses", via: "get"
	match "contact", to: "mains#contact", via: "get"
	match "admin", to: "mains#admin", via: "get"
	resources "mains", only: [:create,:destroy,:update,:edit]
  get '/mains/new/(:parent_id)/(:post_id)/(:post_motivation_id)', to: "mains#new", as: :new_main
  get "admin/all_comments", to: "mains#view_all_comments", as: :view_all_comments
	# Routes for contact page only
	match "create_subscriber", to: "mains#create_subscriber", via: "post"
	match "send_contact", to: "mains#send_contact", via: "post"
	# Route for form of mystory
	patch "admin/mystory/(:id)", to: "mains#edit_mystory_admin",as: :edit_mystory_admin
	# END OF MAINS CONTROLLER
	post '/mains/new/(:parent_id)/(:post_id)/(:post_motivation_id)', to: "mains#new", as: :new_main_dupa
	post "/mains/testonly", to: "mains#testonly"
	
	
	
	
	# POSTS CONTROLLER
  resources :posts
  match "create_post", to: "posts#create_post", via: "get"
  match "create_motivation", to: "posts#create_motivation", via: "get"
  match "save_motivation", to: "posts#save_motivation", via: "post"
  get "/web development/(:id)", to: "posts#learn_showpost", as: :learn_showpost
  get "motivation/(:id)", to: "posts#motivation_showpost", as: :motivation_showpost
  post "/web development/(:id)", to: "posts#learn_showpost", as: :learn_showpost_back
  post "motivation/(:id)", to: "posts#motivation_showpost", as: :motivation_showpost_back
  # FOR ADMIN WEBPAGE
  get "/admin/web development/(:id)/(:ahojmarynarzu)", to: "posts#admin_webdev", as: :admin_webdev
  get "/admin/delete_post/(:id)/(:alibaba)", to: "posts#delete_post", as: :delete_post
  get "/admin/edit_poscik/(:id)/(:alibaba)", to: "posts#edit_poscik", as: :edit_poscik
  patch "/admin/edit(:id)/(:alibaba)", to: "posts#apdejt", as: :apdejt
  get "/admin/delete_post_comment/(:comment_id)", to: "posts#delete_post_comment", as: :delete_post_comment
  get "/admin/edit_post_comment/(:comment_id)", to: "posts#edit_post_comment", as: :edit_post_comment
  patch "/admin/update_edit_post_comment/(:comment_id)", to: "posts#update_edit_post_comment", as: :update_edit_post_comment
	# END OF POSTS CONTROLLER


	# RESTS CONTROLLER
	get "projects/(:id)/(:name)", to: "rests#show_project", as: :show_project
	get "admin_show_projects/(:id)", to: "rests#admin_show_project", as: :admin_show_project
	get "admin_show_projects_delete/(:id)", to: "rests#admin_show_project_delete", as: :admin_show_project_delete
	get "creating_project", to: "rests#creating_project", as: :creating_project
	post "create_project_final", to: "rests#create_project_final", as: :create_project_final
	get "editing_project/(:id)", to: "rests#editing_project",as: :editing_project
	patch "edit_project_final/(:id)", to: "rests#edit_project_final", as: :edit_project_final
	#PRODUCT'S ROUTES
	get "admin/show_all_products", to: "rests#admin_all_products",as: :admin_all_products
	get "admin/create_new_product", to: "rests#create_new_product",as: :create_new_product
	post "admin/create_product_final", to: "rests#create_product_final",as: :create_product_final
	get "admin/edit_product/(:id)", to: "rests#edit_product", as: :edit_product
	patch "admin/final_product", to: "rests#edit_final_product", as: :edit_final_product
	patch "admin/delete_product", to: "rests#delete_product", as: :delete_product
	#CONTACT INFORMATIONS ROUTES
	get "admin/contact_information", to: "rests#contact_information",as: :contact_information
	patch "admin/contact_information_edit", to: "rests#contact_information_edit", as: :contact_information_edit
	#END OF CONTACT INFORMATIONS ROUTES 
	# END OF RESTS CONTROLLER
end

app/controllers/rests_controller.rb
class RestsController < ApplicationController
  before_action :authenticate, except: [:show_project]
  
  def show_project
    @particular_project = Projectsabout.find(params[:id])
  end
  
  def admin_show_project
    @admin_particular_project = Projectsabout.find(params[:id])
  end
  
  def admin_show_project_delete
    @project_to_delete = Projectsabout.find(params[:id])
    @project_to_delete.destroy
    redirect_to admin_path
  end
  
  def creating_project
    @project_to_create = Projectsabout.new
  end
  
  def create_project_final
    @create_project = Projectsabout.new(create_and_edit_project_params)
    @create_project.save
    redirect_to admin_path
  end
  
  def editing_project
    @project_to_edit = Projectsabout.find(params[:id])
  end
  
  def edit_project_final
    @edit_project = Projectsabout.find(params[:id])
    @edit_project.update(create_and_edit_project_params)
    redirect_to admin_path
  end
  
  def admin_all_products
    @show_all_products = Product.all
  end
  
  def create_new_product
    @create_product = Product.new
  end
  
  def create_product_final
    @create_final = Product.new(create_edit_product_final)
    @create_final.save
    redirect_to admin_path
  end
  
  def edit_product
    @edit_product = Product.find(params[:id])
  end
  
  def edit_final_product
    @edit_product_final = Product.find(params[:product][:id])
    @edit_product_final.update(create_edit_product_final)
    redirect_to admin_path
  end
  
  def delete_product
    @product_to_be_deleted = Product.find(params[:product][:id])
    @product_to_be_deleted.destroy
    redirect_to admin_path
  end
  
  def contact_information
    @contact_information_show = Contactinfo.find(1)
  end
  
  def contact_information_edit
    @to_edit = Contactinfo.find(1)
    @to_edit.update(contact_info_params)
    redirect_to admin_path
  end
  
  private
  
    def create_and_edit_project_params
      params.require(:projectsabout).permit(:name,:description,:picture1,:picture2,:picture3,:picture4,:link)
    end
  
    def create_edit_product_final
      params.require(:product).permit(:id,:name,:author,:price,:short_description,:long_description,:affiliate_link,:name_affiliate_link,:picture1,:picture2,:picture3,:picture4)  
    end
    
    def contact_info_params
      params.require(:contactinfo).permit(:name_surname,:facebook,:twitter,:phone_number,:email_address,:github)
    end
    
    def authenticate
      authenticate_or_request_with_http_basic do |name, password|
        name = ENV["ADMIN_LOGIN"] && password == ENV["ADMIN_PASSWORD"]
      end
    end
end

app/helpers/rests_helper.rb
module RestsHelper
end

app/views/rests/admin_all_products.html.erb
<%= stylesheet_link_tag("main_css/admin_all_products")%>
<% content_for(:title, "ADMIN All products") %>

<p><%= link_to("Create new product",create_new_product_path) %></p>

<% @show_all_products.each do |product| %>
	<table class="product-table">
		<tr>
			<td style="border: 1px solid black;">id: <%= product.id %></td>
			<td style="border: 1px solid black;">name: <%= product.name %></td>
		</tr>
		<tr>
			<td style="border: 1px solid black;">author: <%= product.author %></td>
			<td style="border: 1px solid black;">price: <%= product.price %></td>
		</tr>
		<tr>
			<td><%= link_to("Edit",edit_product_path(product.id)) %></td>
			<td>
				<%= form_for(product,:url => delete_product_path) do |eskimos| %>
					<%= eskimos.hidden_field :id %>
					<%= eskimos.submit("Delete",data: {confirm: "Are you sure?"}) %>
				<% end %>
			</td>
			<!--<td><%= link_to("Delete", delete_product_path ,data: {confirm: "Are you sure?"}) %></td>-->
		</tr>
	</table>
<% end %>

app/views/rests/admin_show_project.html.erb
<%= stylesheet_link_tag("main_css/admin_project")%>
<% content_for(:title, "Admin Project") %>
	
<br />

<table class="database_project">
	<tr>
		<td style="width: 30%; border: 1px solid black;"><%= @admin_particular_project.id %></td>
		<td style="width: 70%; border: 1px solid black;"><%= @admin_particular_project.name %></td>
	</tr>
	<tr>
		<td colspan="2" style="border: 1px solid black;"><%= @admin_particular_project.picture1 %></td>	
	</tr>
	<tr>
		<td colspan="2" style="border: 1px solid black;"><%= @admin_particular_project.picture2 %></td>	
	</tr>
	<tr>
		<td colspan="2" style="border: 1px solid black;"><%= @admin_particular_project.picture3 %></td>	
	</tr>
	<tr>
		<td colspan="2" style="border: 1px solid black;"><%= @admin_particular_project.picture4 %></td>	
	</tr>
	<tr>
		<td colspan="2" style="border: 1px solid black;"><%= @admin_particular_project.description %></td>	
	</tr>
	<tr>
		<td><%= link_to("Edit",editing_project_path(@admin_particular_project.id)) %></td>
		<td><%= link_to("Delete",admin_show_project_delete_path(@admin_particular_project.id), data: {confirm: "Are you sure?"})%></td>
	</tr>
</table>

app/views/rests/contact_information.html.erb
<% content_for(:title,"Admin Contact Info") %>

<%= form_for(@contact_information_show,:url => contact_information_edit_path) do |edit| %>
	
	<div>
		<%= edit.label :name_surname %>
		<%= edit.text_field :name_surname %>
	</div>
	<div>
		<%= edit.label :email_address %>
		<%= edit.text_field :email_address %>
	</div>
	<div>
		<%= edit.label :phone_number %>
		<%= edit.text_field :phone_number %>
	</div>
	<div>
		<%= edit.label :facebook %>
		<%= edit.text_field :facebook %>
	</div>
	<div>
		<%= edit.label :twitter %>
		<%= edit.text_field :twitter %>
	</div>
	<div>
		<%= edit.label :github %>
		<%= edit.text_field :github %>
	</div>
	<div>
		<%= edit.submit("Submit",data: {confirm: "Are you sure?"}) %>
	</div>
<% end %>

app/views/rests/create_new_product.html.erb
<% content_for(:title,"ADMIN Create Product") %>

<%= form_for(@create_product,:url => create_product_final_path) do |product| %>

	<%= product.hidden_field :id %>
	
	<div>
		<%= product.label :name %>
		<%= product.text_field :name %>
	</div>
	<div>
		<%= product.label :author %>
		<%= product.text_field :author %>
	</div>
	<div>
		<%= product.label :short_description %>
		<%= product.text_area :short_description %>
	</div>
	<div>
		<%= product.label :long_description %>
		<%= product.text_area :long_description %>
	</div>
	<div>
		<%= product.label :price %>
		<%= product.text_field :price %>
	</div>
	<div>
		<%= product.label :affiliate_link %>
		<%= product.text_field :affiliate_link %>
	</div>
	<div>
		<%= product.label :name_affiliate_link %>
		<%= product.text_field :name_affiliate_link %>
	</div>
	<div>
		<%= product.label :picture1 %>
		<%= product.text_field :picture1 %>
	</div>
	<div>
		<%= product.label :picture2 %>
		<%= product.text_field :picture2 %>
	</div>
	<div>
		<%= product.label :picture3 %>
		<%= product.text_field :picture3 %>
	</div>
	<div>
		<%= product.label :picture4 %>
		<%= product.text_field :picture4 %>
	</div>
	<div>
		<%= product.submit("Submit",data: {confirm: "Are you sure?"}) %>
	</div>
<% end %>

app/views/rests/creating_project.html.erb
<% content_for(:title,"Creating project") %>

<%= form_for(@project_to_create, :url => url_for(:controller => "rests",:action => "create_project_final")) do |project| %>
	<div>	
		<%= project.label :name %>
		<%= project.text_field :name %>
	</div>
	<div>
		<%= project.label :description %>
		<%= project.text_area :description %>
	</div>
	<div>
		<%= project.label :link %>
		<%= project.text_field :link %>
	</div>
	<div>
		<%= project.label :picture1 %>
		<%= project.text_field :picture1 %>
	</div>
	<div>
		<%= project.label :picture2 %>
		<%= project.text_field :picture2 %>
	</div>
	<div>
		<%= project.label :picture3 %>
		<%= project.text_field :picture3 %>
	</div>
	<div>
		<%= project.label :picture4 %>
		<%= project.text_field :picture4 %>
	</div>
	<div>
		<%= project.submit("Submit",data: {confirm: "Are you sure?"}) %>
	</div>
<% end %>

app/views/rests/edit_product.html.erb
<% content_for(:title,"Editing product") %>

<%= form_for(@edit_product,:url => edit_final_product_path(@edit_product.id)) do |f| %>
	
	<%= f.hidden_field :id %>
	
	<div>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	<div>
		<%= f.label :author %>
		<%= f.text_field :author %>
	</div>
	<div>
		<%= f.label :short_description %>
		<%= f.text_area :short_description %>
	</div>
	<div>
		<%= f.label :long_description %>
		<%= f.text_area :long_description %>
	</div>
	<div>
		<%= f.label :price %>
		<%= f.text_field :price %>
	</div>
	<div>
		<%= f.label :affiliate_link %>
		<%= f.text_field :affiliate_link %>
	</div>
	<div>
		<%= f.label :name_affiliate_link %>
		<%= f.text_field :name_affiliate_link %>
	</div>
	<div>
		<%= f.label :picture1 %>
		<%= f.text_field :picture1 %>
	</div>
	<div>
		<%= f.label :picture2 %>
		<%= f.text_field :picture2 %>
	</div>
	<div>
		<%= f.label :picture3 %>
		<%= f.text_field :picture3 %>
	</div>
	<div>
		<%= f.label :picture4 %>
		<%= f.text_field :picture4 %>
	</div>
	<div>
		<%= f.submit("Submit",data: {confirm: "Are you sure?"}) %>
	</div>
<% end %>

app/views/rests/editing_project.html.erb
<% content_for(:title,"Editing project") %>

<%= form_for(@project_to_edit,:url => edit_project_final_path(@project_to_edit.id)) do |project| %>
	<div>
		<%= project.label(:name) %>
		<%= project.text_field(:name) %>
	</div>
	<div>
		<%= project.label(:description) %>
		<%= project.text_area(:description) %>
	</div>
	<div>
		<%= project.label(:picture1) %>
		<%= project.text_field(:picture1) %>
	</div>
	<div>
		<%= project.label(:picture2) %>
		<%= project.text_field(:picture2) %>
	</div>
	<div>
		<%= project.label(:picture3) %>
		<%= project.text_field(:picture3) %>
	</div>
	<div>
		<%= project.label(:picture4) %>
		<%= project.text_field(:picture4) %>
	</div>
	<div>
		<%= project.label(:link) %>
		<%= project.text_field(:link) %>
	</div>
	<div>
		<%= project.submit("Submit",data: {confirm: "Are you sure?"}) %>
	</div>
<% end %>

app/views/rests/show_project.html.erb
<%= stylesheet_link_tag("main_css/show_project")%>
<% content_for(:title, "MK Project") %>
	
	
		<div class="font main-div">
			<center>
				<p><%= @particular_project.name %></p>
				<table>
					<tr>
						<td><%= image_tag(@particular_project.picture1,:alt => "picture",size: "320x240") %></td>
						<td><%= image_tag(@particular_project.picture2,:alt => "picture",size: "320x240") %></td>
					</tr>
				</table>
			</center>
			<p><%= simple_format(@particular_project.description,{},{:wrapper_tag => "div"}) %></p>
			<p><%= link_to @particular_project.link,@particular_project.link %></p>
		</div>
		
	<br />
	<br />